/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface": "#0f131d",
        "surface-dim": "#0f131d",
        "surface-bright": "#353944",
        "surface-container-lowest": "#0a0e18",
        "surface-container-low": "#171b26",
        "surface-container": "#1c1f2a",
        "surface-container-high": "#262a35",
        "surface-container-highest": "#313540",
        "on-surface": "#dfe2f1",
        "on-surface-variant": "#c3c6d6",
        "inverse-surface": "#dfe2f1",
        "inverse-on-surface": "#2c303b",
        "outline": "#8d909f",
        "outline-variant": "#434653",
        "surface-tint": "#b2c5ff",
        "primary": "#b2c5ff",
        "on-primary": "#002c72",
        "primary-container": "#5b8cff",
        "on-primary-container": "#002665",
        "inverse-primary": "#1857c8",
        "secondary": "#4de082",
        "on-secondary": "#003919",
        "secondary-container": "#00b55d",
        "on-secondary-container": "#003e1c",
        "tertiary": "#ffb3b0",
        "on-tertiary": "#670211",
        "tertiary-container": "#ea6767",
        "on-tertiary-container": "#5c000d",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed": "#001847",
        "on-primary-fixed-variant": "#0040a0",
        "secondary-fixed": "#6dfe9c",
        "secondary-fixed-dim": "#4de082",
        "on-secondary-fixed": "#00210c",
        "on-secondary-fixed-variant": "#005227",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#ffb3b0",
        "on-tertiary-fixed": "#410006",
        "on-tertiary-fixed-variant": "#881d24",
        "background": "#0f131d",
        "on-background": "#dfe2f1",
        "surface-variant": "#313540",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "1.25rem",
        "stack-gap": "1rem",
        "section-gap": "2rem",
        "card-inner-padding": "1rem",
        "grid-gutter": "1rem"
      },
      fontFamily: {
        "display": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "numeral-xl": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "display": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "numeral-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
